export const AppError = {
  WRONG_CREDENTIALS: 'Данные не совпадают!',
  INVALID_JWT: 'Неправильный токен!',
  CATEGORY_NOT_FOUND: 'Категория не найдена!',
  CHECKPOINT_NOT_FOUND: 'Пункт пропуска не найден!',
  BRANCH_NOT_FOUND: 'Филиал не найден!',
  FILE_TYPE_NOT_FOUND: 'Тип файла не найден!',
  FILE_NOT_FOUND: 'Файл не найден!',
  GROUP_NOT_FOUND: 'Группа не найдена!',
  ORDER_NOT_FOUND: 'Заказ не найден!',
  ORDER_STATUS_NOT_FOUND: 'Статус заказа не найден!',
  ORDER_BAD_REQUEST: 'Необходимо указать задачу или название задачи!',
  ORGANIZATION_NOT_FOUND: 'Организация не найдена!',
  ORGANIZATION_TYPE_NOT_FOUND: 'Тип организации не найден!',
  PERMISSION_NOT_FOUND: 'Разрешение не найдено!',
  PERSON_NOT_FOUND: 'Данные пользователя не найдены!',
  PRIORITY_NOT_FOUND: 'Приоритет не найден!',
  REPORT_NOT_FOUND: 'Отчет не найден!',
  ROLE_NOT_FOUND: 'Роль не найдена!',
  ROLE_PERMISSION_NOT_FOUND: 'Запись не найдена!',
  TASK_NOT_FOUND: 'Задача не найдена!',
  TRANSACTION_HISTORY_NOT_FOUND: 'Запись в истории не найдена!',
  USER_EXECUTOR_NOT_FOUND: 'Пользователь (исполнитель) не найден!',
  USER_CREATOR_NOT_FOUND: 'Пользователь (создатель) не найден!',
  USER_NOT_FOUND: 'Пользователь не найден!',
  USER_EMAIL_EXISTS: 'Пользователь с таким email уже существует!',
  PROPERTY_NAME_NOT_FOUND: 'Название характеристики не найдено!',
  PROPERTY_VALUE_NOT_FOUND: 'Значение характеристики не найдено!',
  PERSON_STATUS_NOT_FOUND: 'Статус пользователя не найден!',
  GENDER_NOT_FOUND: 'Пол не найден!',
}